const Skills = () => {
  return (
    <div>
      <h2>Skills</h2>
      <table>
        <tr>
          <th>項目(クリックでroadmap.shへ)</th>
          <th>仕事での経験年数</th>
        </tr>
        <tr>
          <td>
            <a
              href="https://roadmap.sh/git-github?s=67b2a46b98abd86c99d44f13"
              target="_blank"
            >
              Git・GitHub
            </a>
          </td>
          <td>7年</td>
        </tr>
        <tr>
          <td>C#</td>
          <td>5年</td>
        </tr>
        <tr>
          <td>
            <a
              href="https://roadmap.sh/javascript?s=67b2a46b98abd86c99d44f13"
              target="_blank"
            >
              JavaScript
            </a>
          </td>
          <td>未経験</td>
        </tr>
        <tr>
          <td>
            <a
              href="https://roadmap.sh/typescript?s=67b2a46b98abd86c99d44f13"
              target="_blank"
            >
              TypeScript
            </a>
          </td>
          <td>2年</td>
        </tr>
        <tr>
          <td>Java</td>
          <td>1年</td>
        </tr>
        <tr>
          <td>
            <a
              href="https://roadmap.sh/game-developer?s=67b2a46b98abd86c99d44f13"
              target="_blank"
            >
              ゲーム開発者
            </a>
          </td>
          <td>5年</td>
        </tr>
        <tr>
          <td>
            <a
              href="https://roadmap.sh/frontend?s=67b2a46b98abd86c99d44f13"
              target="_blank"
            >
              フロントエンド開発者
            </a>
          </td>
          <td>未経験</td>
        </tr>
        <tr>
          <td>
            <a
              href="https://roadmap.sh/react?s=67b2a46b98abd86c99d44f13"
              target="_blank"
            >
              React開発者
            </a>
          </td>
          <td>未経験</td>
        </tr>
      </table>
      <p>
        ※roadmap.shの説明：取り消し線付きグレーの項目：完了 /
        取り消し線付き青の項目：スキップ / 紫の項目：進行中 / その他：未習得
      </p>
    </div>
  );
};

export default Skills;
